// GENERATED by tools/generators/genMapAlign.ts — do not edit by hand.
//
// Translation applied to each terrain .glb so it lands on the sim's grid
// frame, measured by correlating the mesh's vertices against MapData.heights
// (`match` = fraction that landed exactly on their heightfield sample). The
// recorded bounds are the ones the offsets were measured against;
// render/meshMap.ts compares them at load time and shouts if a regenerated
// asset has drifted, so a silently misplaced arena is not possible.
//
// Re-run `bun run gen:mapalign` after replacing any arena .glb or heightfield.

export interface MapAlign {
  /** Offset added to the loaded gltf.scene position, in sim world units. */
  readonly x: number;
  readonly y: number;
  readonly z: number;
  /** Mesh bounds the offsets were measured against — the drift guard. */
  readonly minX: number;
  readonly minY: number;
  readonly minZ: number;
  readonly maxX: number;
  readonly maxY: number;
  readonly maxZ: number;
  /** Fraction of sampled vertices that matched the heightfield exactly. */
  readonly match: number;
}

export const MAP_ALIGN: Readonly<Record<string, MapAlign>> = {
  "urban-jungle": {
    x: 120.5,
    y: 0,
    z: 136.5,
    minX: -104.5,
    minY: -3.90625,
    minZ: -136.5,
    maxX: 103.5,
    maxY: 2.78125,
    maxZ: 103.5,
    match: 0.944,
  },
  "proving-ground": {
    x: 120.5,
    y: 0,
    z: 136.5,
    minX: -104.5,
    minY: -3.96875,
    minZ: -136.5,
    maxX: 103.5,
    maxY: 3.96875,
    maxZ: 103.5,
    match: 0.951,
  },
  "la-cantina": {
    x: 112.5,
    y: 0,
    z: 128.5,
    minX: -96.5,
    minY: -2.5,
    minZ: -128.5,
    maxX: 95.5,
    maxY: 3.90625,
    maxZ: 95.5,
    match: 0.939,
  },
  "bug-hunt": {
    x: 120.5,
    y: 0,
    z: 136.5,
    minX: -104.5,
    minY: -3.96875,
    minZ: -136.5,
    maxX: 103.5,
    maxY: 3.96875,
    maxZ: 103.5,
    match: 0.955,
  },
  "hollywood-keys": {
    x: 152.5,
    y: 0,
    z: 136.5,
    minX: -136.5,
    minY: -2.96875,
    minZ: -136.5,
    maxX: 135.5,
    maxY: 3.90625,
    maxZ: 103.5,
    match: 0.991,
  },
  "venice-beach": {
    x: 144.5,
    y: 0,
    z: 160.5,
    minX: -128.5,
    minY: -3.96875,
    minZ: -160.5,
    maxX: 127.5,
    maxY: 3.5,
    maxZ: 127.5,
    match: 0.999,
  },
};
