// GENERATED by tools/generators/genSfx.ts — do not edit by hand.
//
// Cue -> committed original-sound URL, for the additive upgrade in
// audio/engine.ts: every cue renders from the sfxr synth at unlock, and only the
// cues listed here are then replaced by their file. Loudness is already baked
// into each file by the generator, so the runtime just swaps the buffer.
//
// Empty is the normal state while the cue picking is an open ear pass (#27) —
// see tools/generators/sfx/manifest.ts. Re-run `bun run gen:sfx` after editing
// that manifest.

export const SFX_FILES: Readonly<Record<string, string>> = {};
