// Road traversability: the three path segments a produced unit actually travels
// on a Precinct Assault arena (rules.md §9), walked with the sim's own stepper.
//
// AUTHORING AND VERIFICATION ONLY. Nothing here runs inside a tick — it is a
// replay of `units.ts` movement over a map, used by stage 2 of the arena
// pipeline (tools/generators/enrichArena.ts) to decide which wall bits block a
// road, and by packages/sim/test to pin that the roads stay walkable. It lives
// in the sim, next to the rule it mirrors, for the reason `worstUphillRise`
// does: a second copy in the generator would agree today and quietly stop
// agreeing the first time movement changes.
//
// WHY IT EXISTS
// A produced unit travels three kinds of segment, and stage 2 used to validate
// only the middle one:
//
//   1. production console -> the graph entry node          (a straight beeline)
//   2. node -> node along the committed signposts          (the Cnet edges)
//   3. the chain's last node -> the enemy gate             (a straight beeline)
//
// Segments 1 and 3 are generated by the sim, not by the extracted data, so
// nothing in the data says they must be clear — and on three of the four
// arenas they were not. Units could not leave their own base.
//
// It also matters HOW an edge is walked. `crossesWallX/Y` decide a diagonal
// crossing from the position at the START of the axis move, so which cell row
// the test lands in depends on the step length, and a road running exactly
// along a lattice line (the original's Cnet does this constantly) can be
// blocked by a wall bit belonging to the column next to it. So traversability
// is asserted at every step length a ground unit uses, and across a narrow
// lateral band rather than on the centre line alone.

import {
  CORE_ATTACK_RADIUS,
  GRAPH_WAYPOINT_RADIUS,
  JUGGERNAUT_SPEED,
  RUNNER_SPEED,
  TICK_DT,
} from "./balance";
import { crossesWallX, crossesWallY } from "./collision";
import { type MapData, worldExtent } from "./map";

/**
 * Per-tick travel distances of the ground archetypes, slowest last.
 *
 * A road has to be walkable at every one of these, not just at some convenient
 * probe resolution: the wall test is evaluated once per axis per tick, so the
 * step length decides where along a diagonal the test samples.
 */
export const GROUND_STEPS: readonly number[] = [RUNNER_SPEED * TICK_DT, JUGGERNAUT_SPEED * TICK_DT];

/**
 * Lateral half-width of the corridor a road is opened across, in metres.
 *
 * Small on purpose: this is not "widen the streets", it is "a walker whose
 * position differs from the centre line by a rounding error must not be stopped
 * by the wall bit on the other side of the line". 5 cm is well under the 0.35 m
 * step snap and the 2.4 m separation radius, so it cannot open a gap between
 * two cells that are genuinely walled apart.
 */
export const ROAD_HALF_WIDTH = 0.05;

/** Consecutive no-progress ticks after which a walker is called stuck. */
const STUCK_TICKS = 30;

/**
 * Segment length, built from the allowed arithmetic only: `+ - * /` and
 * `Math.sqrt` (CLAUDE.md determinism rule 2, which is what makes `Math.sqrt`
 * usable — it is IEEE-exact). `Math.hypot` would be the obvious spelling and
 * determinismGuard.test.ts rejects it for every file in this package, along with
 * the rest of the engine-dependent `Math.*` surface.
 *
 * That guard covers this file even though nothing here runs inside a tick, and
 * the coverage is worth having: what this measures decides which wall bits the
 * committed maps carry, so it has to give the same answer on every engine.
 */
function length(dx: number, dy: number): number {
  return Math.sqrt(dx * dx + dy * dy);
}

/** A wall bit that stopped a walker. */
export interface WallHit {
  /** 0 = vertical wall (`wallsV[row * size + line]`), 1 = horizontal (`wallsH[line * size + col]`). */
  readonly axis: 0 | 1;
  /** Grid line the move crossed. */
  readonly line: number;
  /** Row (axis 0) or column (axis 1) the crossing happened in. */
  readonly cross: number;
}

/** Where a walk ended. */
export interface WalkResult {
  readonly reached: boolean;
  readonly x: number;
  readonly y: number;
  /** Ticks spent. */
  readonly ticks: number;
}

function clampCell(v: number, size: number): number {
  if (v < 0) return 0;
  return v > size - 2 ? size - 2 : v;
}

/** The wall bit a blocked ±x move ran into. */
function hitX(map: MapData, x: number, nx: number, y: number): WallHit {
  const inv = 1 / map.cellSize;
  const gi0 = Math.floor(x * inv);
  const gi1 = Math.floor(nx * inv);
  return { axis: 0, line: gi0 < gi1 ? gi1 : gi0, cross: clampCell(Math.floor(y * inv), map.size) };
}

/** The wall bit a blocked ±y move ran into. */
function hitY(map: MapData, x: number, y: number, ny: number): WallHit {
  const inv = 1 / map.cellSize;
  const gj0 = Math.floor(y * inv);
  const gj1 = Math.floor(ny * inv);
  return { axis: 1, line: gj0 < gj1 ? gj1 : gj0, cross: clampCell(Math.floor(x * inv), map.size) };
}

/**
 * Walks a straight segment exactly the way `stepAndSnap` moves a ground unit:
 * axis-separated, x first, y against the already-updated x, clamped to the map,
 * and blocked moves slide instead of stopping.
 *
 * Read-only — this is the question "can a unit get from a to b", and the answer
 * has to include the sliding, because the sim slides.
 */
export function walkLine(
  map: MapData,
  ax: number,
  ay: number,
  bx: number,
  by: number,
  step: number,
): WalkResult {
  const extent = worldExtent(map);
  const clamp = (v: number): number => (v < 0 ? 0 : v > extent ? extent : v);
  let x = ax;
  let y = ay;
  let stuck = 0;
  // Generous: a walker that slides along a wall covers more ground than the
  // straight-line distance, and the budget only has to exclude infinite loops.
  const budget = Math.ceil(length(bx - ax, by - ay) / step) * 8 + 200;
  for (let t = 0; t < budget; t++) {
    const dx = bx - x;
    const dy = by - y;
    const d2 = dx * dx + dy * dy;
    if (d2 <= step * step) return { reached: true, x, y, ticks: t };
    const inv = 1 / Math.sqrt(d2);
    const px = x;
    const py = y;
    const nx = clamp(x + dx * inv * step);
    if (!crossesWallX(map, x, nx, y)) x = nx;
    const ny = clamp(y + dy * inv * step);
    if (!crossesWallY(map, x, y, ny)) y = ny;
    if (Math.abs(x - px) > 1e-9 || Math.abs(y - py) > 1e-9) {
      stuck = 0;
      continue;
    }
    if (++stuck > STUCK_TICKS) return { reached: false, x, y, ticks: t };
  }
  return { reached: false, x, y, ticks: budget };
}

/**
 * Walks the ideal straight line and reports every wall bit in the way, so the
 * caller can open them (stage 2's road carve).
 *
 * Deliberately NOT the sliding walker: a blocked move is reported and then taken
 * anyway, so the path stays the straight line between the two points instead of
 * wandering off along whatever it bumped into. Opening exactly this set is the
 * stronger invariant — with the line clear, `walkLine` never has to slide at all,
 * which is what makes the traversal reproducible rather than lucky.
 */
export function openLine(
  map: MapData,
  ax: number,
  ay: number,
  bx: number,
  by: number,
  step: number,
  onWall: (hit: WallHit) => void,
): void {
  const extent = worldExtent(map);
  const clamp = (v: number): number => (v < 0 ? 0 : v > extent ? extent : v);
  let x = ax;
  let y = ay;
  const budget = Math.ceil(length(bx - ax, by - ay) / step) + 8;
  for (let t = 0; t < budget; t++) {
    const dx = bx - x;
    const dy = by - y;
    const d2 = dx * dx + dy * dy;
    if (d2 <= step * step) return;
    const inv = 1 / Math.sqrt(d2);
    const nx = clamp(x + dx * inv * step);
    if (crossesWallX(map, x, nx, y)) onWall(hitX(map, x, nx, y));
    x = nx;
    const ny = clamp(y + dy * inv * step);
    if (crossesWallY(map, x, y, ny)) onWall(hitY(map, x, y, ny));
    y = ny;
  }
}

/** Unit normal of a segment, for the lateral offsets. Zero-length gives (0,0). */
function normal(ax: number, ay: number, bx: number, by: number): [number, number] {
  const dx = bx - ax;
  const dy = by - ay;
  const len = length(dx, dy);
  if (len < 1e-6) return [0, 0];
  return [-dy / len, dx / len];
}

/**
 * Every (step length, lateral offset) pair a segment has to survive: the centre
 * line and one offset either side, at each ground unit's own step.
 */
export function roadProbes(
  ax: number,
  ay: number,
  bx: number,
  by: number,
): readonly { readonly ox: number; readonly oy: number; readonly step: number }[] {
  const [nx, ny] = normal(ax, ay, bx, by);
  const out: { ox: number; oy: number; step: number }[] = [];
  for (const step of GROUND_STEPS) {
    out.push({ ox: 0, oy: 0, step });
    out.push({ ox: nx * ROAD_HALF_WIDTH, oy: ny * ROAD_HALF_WIDTH, step });
    out.push({ ox: -nx * ROAD_HALF_WIDTH, oy: -ny * ROAD_HALF_WIDTH, step });
  }
  return out;
}

/** True when a straight segment is walkable at every probe, without changing walls. */
export function segmentWalkable(
  map: MapData,
  ax: number,
  ay: number,
  bx: number,
  by: number,
): boolean {
  for (const p of roadProbes(ax, ay, bx, by)) {
    if (!walkLine(map, ax + p.ox, ay + p.oy, bx + p.ox, by + p.oy, p.step).reached) return false;
  }
  return true;
}

/** The last node of a team's committed signpost chain (its road's far end). */
export function chainGoal(map: MapData, team: number): number {
  const g = map.laneGraph;
  if (g === undefined) return -1;
  const n = g.nodes.length;
  let at = g.entry[team];
  for (let guard = 0; guard <= n; guard++) {
    const next = g.nextHopA[team * n + at];
    if (next < 0) return at;
    at = next;
  }
  return at;
}

/** Does following `nextHopA` from `node` end at the team's chain goal? */
export function onChain(map: MapData, team: number, node: number, goal: number): boolean {
  const g = map.laneGraph;
  if (g === undefined) return false;
  const n = g.nodes.length;
  let at = node;
  for (let guard = 0; guard <= n; guard++) {
    if (at === goal) return true;
    const next = g.nextHopA[team * n + at];
    if (next < 0) return false;
    at = next;
  }
  return false;
}

/** Where a road walk ended, and how far short of the objective it stopped. */
export interface RoadWalk extends WalkResult {
  /** Metres from the enemy core at the end of the walk. */
  readonly distanceToCore: number;
  /** Which segment it was on: 0 = console -> entry, 1 = graph, 2 = gate beeline. */
  readonly leg: 0 | 1 | 2;
  /** Target node when it stopped, or -1 past the end of the chain. */
  readonly node: number;
}

/**
 * Walks one unopposed produced unit from its production console to the enemy
 * core, following the committed signposts exactly as `moveGroundUnit` does.
 *
 * `reached` means it got inside `CORE_ATTACK_RADIUS`, i.e. it could damage the
 * core. No combat, no separation, no forks: `nextHopA` only, since `nextHopB` is
 * a coin flip the sim owns and every fork's alternative is validated as an edge
 * in its own right.
 */
export function walkRoad(map: MapData, team: number, step: number): RoadWalk {
  const g = map.laneGraph;
  const core = map.bases[team ^ 1].core;
  const gate = map.bases[team ^ 1].gate;
  const start = map.bases[team].groundConsole;
  if (g === undefined) {
    const w = walkLine(map, start.x, start.y, gate.x, gate.y, step);
    return {
      ...w,
      distanceToCore: length(w.x - core.x, w.y - core.y),
      leg: 2,
      node: -1,
    };
  }
  const n = g.nodes.length;
  const extent = worldExtent(map);
  const clamp = (v: number): number => (v < 0 ? 0 : v > extent ? extent : v);
  let x = start.x;
  let y = start.y;
  let node = g.entry[team];
  let leg: 0 | 1 | 2 = 0;
  let stuck = 0;
  // Long enough for the longest road at the slowest step, with slack for wall
  // sliding; a stuck walker exits on STUCK_TICKS long before this.
  const budget = 30 * 60 * 10;
  for (let t = 0; t < budget; t++) {
    const dc = length(x - core.x, y - core.y);
    if (dc <= CORE_ATTACK_RADIUS) {
      return { reached: true, x, y, ticks: t, distanceToCore: dc, leg, node };
    }
    // One hop per tick, then move toward whatever the hop left us aiming at —
    // the order moveGroundUnit uses.
    if (node >= 0) {
      const nd = g.nodes[node];
      const ddx = nd.x - x;
      const ddy = nd.y - y;
      if (ddx * ddx + ddy * ddy <= GRAPH_WAYPOINT_RADIUS * GRAPH_WAYPOINT_RADIUS) {
        node = g.nextHopA[team * n + node];
        leg = node < 0 ? 2 : 1;
      }
    }
    const target = node >= 0 ? g.nodes[node] : gate;
    const tx = target.x;
    const ty = target.y;
    const dx = tx - x;
    const dy = ty - y;
    const d2 = dx * dx + dy * dy;
    const px = x;
    const py = y;
    if (d2 > 0.0001) {
      const inv = 1 / Math.sqrt(d2);
      const nx = clamp(x + dx * inv * step);
      if (!crossesWallX(map, x, nx, y)) x = nx;
      const ny = clamp(y + dy * inv * step);
      if (!crossesWallY(map, x, y, ny)) y = ny;
    }
    if (Math.abs(x - px) > 1e-9 || Math.abs(y - py) > 1e-9) {
      stuck = 0;
      continue;
    }
    if (++stuck <= STUCK_TICKS) continue;
    return {
      reached: false,
      x,
      y,
      ticks: t,
      distanceToCore: length(x - core.x, y - core.y),
      leg,
      node,
    };
  }
  return {
    reached: false,
    x,
    y,
    ticks: budget,
    distanceToCore: length(x - core.x, y - core.y),
    leg,
    node,
  };
}
