// SFX cue pipeline (#27, assets.md §5).
//
//   raw Cwav WAV -> trim -> downmix to mono -> peak-normalise to -3 dBFS
//   -> optional manual gain -> packages/client/public/sfx/<cue>.wav
//   -> packages/client/src/audio/sfxFiles.generated.ts
//
// Driven by sfx/manifest.ts. That manifest is EMPTY today (see its header: the
// extracted sounds carry no semantic labels, so which one is "shot" is an ear
// question), and an empty run is the normal, valid case — it writes no audio and
// an empty lookup, which leaves every cue on the sfxr synth exactly as before.
//
// Normalisation happens here rather than at runtime for the same reason the
// synth bakes `soundVol` into its PCM: one cue's loudness must not depend on
// when it happens to be decoded.
//
// WAV in / WAV out, hand-rolled: the generators workspace has no audio deps, and
// PCM needs none. Committing .wav rather than .ogg also keeps the toolchain free
// of an encoder — the browser decodes both, and these files are small.
//
// Usage: bun run gen:sfx   (from the repo root)

import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { SFX_CUES, type SfxCueSpec } from "./sfx/manifest";
import { decodeWav, encodeWav } from "./sfx/wav";

const RAW_DIR = join(import.meta.dir, "sfx", "raw");
const OUT_AUDIO = join(import.meta.dir, "..", "..", "packages", "client", "public", "sfx");
const OUT_TS = join(
  import.meta.dir,
  "..",
  "..",
  "packages",
  "client",
  "src",
  "audio",
  "sfxFiles.generated.ts",
);

/** Peak target for the written file. -3 dBFS leaves headroom for voice sums. */
const PEAK_TARGET = 10 ** (-3 / 20);

interface Report {
  cue: string;
  seconds: string;
  rate: number;
  peakBefore: string;
  gain: string;
  bytes: number;
}

async function processCue(spec: SfxCueSpec): Promise<Report> {
  const raw = new Uint8Array(await Bun.file(join(RAW_DIR, spec.raw)).arrayBuffer());
  const { rate, samples } = decodeWav(raw);

  const from = Math.min(samples.length, Math.max(0, Math.round((spec.trimStart ?? 0) * rate)));
  const to = Math.max(from, samples.length - Math.round((spec.trimEnd ?? 0) * rate));
  const trimmed = samples.subarray(from, to);
  if (trimmed.length === 0) throw new Error(`${spec.cue}: trimmed to nothing`);

  let peak = 0;
  for (const v of trimmed) {
    const a = Math.abs(v);
    if (a > peak) peak = a;
  }
  if (peak === 0) throw new Error(`${spec.cue}: silent after trim`);
  const gain = (PEAK_TARGET / peak) * (spec.gain ?? 1);

  const out = new Float32Array(trimmed.length);
  for (let i = 0; i < trimmed.length; i++) out[i] = trimmed[i] * gain;

  const wav = encodeWav({ rate, samples: out });
  await mkdir(OUT_AUDIO, { recursive: true });
  await Bun.write(join(OUT_AUDIO, `${spec.cue}.wav`), wav);

  return {
    cue: spec.cue,
    seconds: (out.length / rate).toFixed(3),
    rate,
    peakBefore: peak.toFixed(3),
    gain: gain.toFixed(3),
    bytes: wav.byteLength,
  };
}

const reports: Report[] = [];
for (const spec of SFX_CUES) {
  reports.push(await processCue(spec));
}

// Emitted Biome-clean either way: an empty record must collapse to `{}` or
// `bun run lint` fails on the generator's own output.
const entries = SFX_CUES.map((s) => `  ${JSON.stringify(s.cue)}: "/sfx/${s.cue}.wav",`);
const body = entries.length > 0 ? `{\n${entries.join("\n")}\n}` : "{}";
const generated = `// GENERATED by tools/generators/genSfx.ts — do not edit by hand.
//
// Cue -> committed original-sound URL, for the additive upgrade in
// audio/engine.ts: every cue renders from the sfxr synth at unlock, and only the
// cues listed here are then replaced by their file. Loudness is already baked
// into each file by the generator, so the runtime just swaps the buffer.
//
// Empty is the normal state while the cue picking is an open ear pass (#27) —
// see tools/generators/sfx/manifest.ts. Re-run \`bun run gen:sfx\` after editing
// that manifest.

export const SFX_FILES: Readonly<Record<string, string>> = ${body};
`;
await Bun.write(OUT_TS, generated);

if (reports.length === 0) {
  console.log("gen:sfx: manifest is empty — wrote an empty SFX_FILES, no audio files.");
  console.log("         Every cue stays on the sfxr synth (see sfx/manifest.ts for why).");
} else {
  console.log("cue        secs     rate   peak   gain   KB");
  for (const r of reports) {
    console.log(
      `${r.cue.padEnd(11)}${r.seconds.padEnd(9)}${String(r.rate).padEnd(7)}` +
        `${r.peakBefore.padEnd(7)}${r.gain.padEnd(7)}${(r.bytes / 1024).toFixed(0)}`,
    );
  }
}
